# These are supported funding model platforms

# GitHub Sponsors
# github: [username]

# Open Collective
# open_collective: hydroqc

# Ko-fi
# ko_fi: hydroqc

# Patreon
# patreon: hydroqc

# Custom URL
github: mdallaire
custom: ["https://hydroqc.ca/fr/dons/"]
