blueprint:
  name: Hydro-Québec Flex D (Événements de calendrier)
  description: '# Gestion des événements de pointe critique "Flex D" via calendrier.


    Ce blueprint utilise les événements de calendrier créés automatiquement par l''intégration
    Hydro-Québec pour déclencher vos automatisations lors des périodes de pointe critique.


    **Prérequis** : Vous devez avoir configuré un calendrier dans les options de
    votre intégration Hydro-Québec Flex-D (DPC).


    ## Configuration


    ### Sélection du calendrier

    Sélectionnez le calendrier que vous avez configuré dans l''intégration Hydro-Québec
    pour recevoir les événements de pointe critique.


    ### Période de pré-chauffage

    Définissez combien de temps avant le début de l''événement vous souhaitez commencer
    le pré-chauffage de votre résidence (en minutes).


    ### Actions


    Définition des actions à effectuer dans Home-Assistant lors de chaque début et
    fin de périodes.


    Vous trouverez plus de détails sur les logiques applicables pour Flex-D

    dans la [documentation Hydro-Québec](https://www.hydroquebec.com/residentiel/espace-clients/tarifs/tarif-flex-d.html).

    '
  domain: automation
  input:
    hydroqc_calendar:
      name: Calendrier Hydro-Québec
      description: Sélectionnez le calendrier configuré dans l'intégration Hydro-Québec pour les événements de pointe critique
      selector:
        entity:
          domain: calendar
          multiple: false
    preheat_offset:
      name: Délai de pré-chauffage (minutes)
      description: Temps avant le début de l'événement pour commencer le pré-chauffage (ex. 120 minutes)
      default: 120
      selector:
        number:
          min: 0
          max: 240
          step: 15
          unit_of_measurement: minutes
          mode: slider
    pre_heat_start_action:
      name: Action de pré-chauffage
      description: Actions à effectuer avant la période de pointe critique pour
        pré-chauffer votre résidence.
      default: []
      selector:
        action: {}
    critical_peak_start_action:
      name: Action début pointe critique
      description: Actions à effectuer au début de la période de pointe critique pour
        réduire votre consommation électrique.
      default: []
      selector:
        action: {}
    critical_peak_end_action:
      name: Action fin pointe critique
      description: Actions à effectuer à la fin de la période de pointe critique pour
        rétablir votre consommation normale.
      default: []
      selector:
        action: {}
  source_url: https://github.com/hydroqc/hydroqc-ha/blob/main/blueprints/flex-d-calendar.yaml
mode: parallel
trigger:
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: !input preheat_offset
    id: pre_heat_trigger
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    id: peak_start_trigger
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: end
    id: peak_end_trigger
action:
  - choose:
      - conditions:
          - condition: trigger
            id: pre_heat_trigger
        sequence: !input pre_heat_start_action
      - conditions:
          - condition: trigger
            id: peak_start_trigger
        sequence: !input critical_peak_start_action
      - conditions:
          - condition: trigger
            id: peak_end_trigger
        sequence: !input critical_peak_end_action
